steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/long-canto-398517/server', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/long-canto-398517/server']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'your-cloud-run-service',
        '--image',
        'gcr.io/your-project-id/your-image-name:your-tag',
        '--platform',
        'managed',
      ]
images:
  - 'gcr.io/long-canto-398517/server'
