steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/long-canto-398517/server', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/long-canto-398517/server']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'your-cloud-run-service',
        '--image',
        'gcr.io/long-canto-398517/server',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--traffic',
        '{"revisionName":"my-service-00002-quk","percent":50}',
        '--service-account',
        'serviceaccountcloudrun@long-canto-398517.iam.gserviceaccount.com',
      ]
images:
  - 'gcr.io/long-canto-398517/server'
